
version: 2
.conan-steps: &conan-steps
  steps:
    - checkout
    - run:
        name: Update Conan package
        command: |
          chmod +x .circleci/install.sh
          .circleci/install.sh
    - run:
        name: Build recipe
        command: |
          chmod +x .circleci/run.sh
          .circleci/run.sh
        environment:
          CONAN_REFERENCE: "openstudio-ruby/2.5.5"
          CONAN_USERNAME: "lefticus"
          CONAN_CHANNEL: "testing"
          
jobs:

  gcc-49:
      docker:
        - image: conanio/gcc49
      environment:
        - CONAN_GCC_VERSIONS: "4.9"
      <<: *conan-steps

  gcc-5:
      docker:
        - image: conanio/gcc5
      environment:
        - CONAN_GCC_VERSIONS: "5"
      <<: *conan-steps

  gcc-6:
      docker:
        - image: conanio/gcc6
      environment:
        - CONAN_GCC_VERSIONS: "6"
      <<: *conan-steps

  gcc-7:
      docker:
        - image: conanio/gcc7
      environment:
        - CONAN_GCC_VERSIONS: "7"
      <<: *conan-steps

  gcc-8:
      docker:
        - image: conanio/gcc8
      environment:
        - CONAN_GCC_VERSIONS: "8"
      <<: *conan-steps


workflows:
  version: 2
  build_and_test:
    jobs:
      - gcc-49
      - gcc-5
      - gcc-6
      - gcc-7
      - gcc-8


